import React from 'react'
import "./PrivacyPolicy.css"
import { Card } from 'react-bootstrap'

const PrivacyPolicy = () => {

  return (

    <Card className='conditionscard'>
    <Card.Header className='conditions-header'>Privacy Policy</Card.Header>
    <Card.Body>

      <blockquote className="blockquote mb-0">
      <footer className="blockquote-footer">
        Date of last update: <cite title="Source Title">December 06, 2023</cite>
        </footer>

        <p className='conditions-text'>

          {' '}

          <h6>Interpretation and Definitions</h6>

          Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

 

Definitions

For the purposes of this Privacy Policy:

 

Account means a unique account created for You to access our Service or parts of our Service.

 

Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

 

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Purrfect Pets.

 

Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.

 

<h6>Country refers to: Albania</h6>

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

 

Personal Data is any information that relates to an identified or identifiable individual.

 

Service refers to the Website.

 

Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

 

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

 

Website refers to Purrfect Pets, accessible from http://localhost:3000

 

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

 

Collecting and Using Your Personal Data

Types of Data Collected

Personal Data

While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

 

Email address

 

First name and last name

 

Address, State, Province, ZIP/Postal code, City

 

Usage Data

 

<h6>Usage Data</h6>

Usage Data is collected automatically when using the Service.

 

Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

 

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

 

We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.

 

<h6>Use of Your Personal Data</h6>

The Company may use Personal Data for the following purposes:

 

To provide and maintain our Service, including to monitor the usage of our Service.

 

To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.

 

For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.

 

To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

 

To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

 

To manage Your requests: To attend and manage Your requests to Us.

 

For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.

 

For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

 

<h6>Children's Privacy</h6>

Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

 

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

<h6>Links to Other Websites</h6>

Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

 

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

 

<h6>Changes to this Privacy Policy</h6>

We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

 

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

 

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

 

<h6>Contact Us</h6>

If you have any questions about this Privacy Policy, You can contact us:

          {' '}
        </p>
        <footer className="blockquote-footer">
        By email:  <cite title="Source Title">purrfectpets32@gmail.com</cite>
        </footer>

        <footer className="blockquote-footer">
        By visiting this page on our website: <cite title="Source Title">https://www.purrfectpets.com/contact</cite>
        </footer>

        <footer className="blockquote-footer">
        By phone number: <cite title="Source Title">+44 567 4677</cite>
        </footer>

      </blockquote>

    </Card.Body>
  </Card>

  )

}

 

export default PrivacyPolicy